env:
- TARGET=debian-jessie
- TARGET=debian-testing
- TARGET=debian-unstable
- TARGET=ubuntu-trusty
- TARGET=ubuntu-xenial
- TARGET=ubuntu-yakkety
- TARGET=debian-pip
sudo: required
services:
- docker
script:
- ./build-and-run.sh $TARGET
notifications:
  irc:
    channels:
      - "irc.oftc.net#ooni"
    on_success: change
    on_failure: change
    skip_join: true
    template:
      - "%{repository} (%{commit}): %{message} Diff: %{compare_url}"
      - "Build: %{build_url}"
  email:
    recipients:
      - irl@torproject.org
      - contact@openobservatory.org
    on_success: change
    on_failure: change
